# Generated by Django 3.0.1 on 2020-01-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Room number')),
                ('max_guests', models.IntegerField(verbose_name='Maximum guests')),
                ('is_kept', models.BooleanField(verbose_name='is kept')),
                ('owner', models.ForeignKey(on_delete=models.SET('free'), to='mycore.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_cnt', models.IntegerField(verbose_name='Count guests')),
                ('key_in_date', models.DateTimeField(db_index=True, verbose_name='Date and time')),
                ('key_out_date', models.DateTimeField(db_index=True, verbose_name='Date and time')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Room')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Tenant')),
            ],
        ),
    ]
