# Generated by Django 3.0.1 on 2020-01-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0002_journal_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=models.SET('free'), to='mycore.Tenant'),
        ),
    ]
