# Generated by Django 3.0.1 on 2020-01-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0003_auto_20200101_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('free'), to='mycore.Tenant'),
        ),
    ]
