# Generated by Django 3.0.1 on 2020-01-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0005_auto_20200101_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycore.Room'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tenant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycore.Tenant'),
        ),
    ]
