# Generated by Django 3.0.1 on 2020-01-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0006_auto_20200101_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_kept',
        ),
        migrations.AddField(
            model_name='room',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='is free'),
        ),
    ]
