# Generated by Django 3.0.1 on 2020-01-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0007_auto_20200101_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
